-- PAULO ANDRADE 18/04/2022 -- 

SELECT A.PRODUTO																					AS PRODUTO,
       A.DESCRICAO																					AS DESCRICAO,
	   B.EAN																						AS EAN,
	   C.DESCRICAO																					AS MARCA,
	   ROUND(CONVERT(FLOAT,AVG(D.CUSTO_CONTABIL)),2)												AS CUSTO_CONTABIL,
	   CONVERT(FLOAT, E.PRECO_FABRICA)																AS PRECO_FABRICA,
	   CONVERT(FLOAT, E.DESCONTO_PADRAO)                                                            AS DESCONTO_PADRAO,
	   CONVERT(FLOAT, E.PRECO_VENDA)																AS PRECO_VENDA,
	   ((E.PRECO_VENDA - AVG(D.CUSTO_CONTABIL)) / E.PRECO_VENDA)									AS MARGEM_ATUAL,
	   G.ALIQUOTA_ICMS                                                                              AS ALIQUOTA_ICMS,
	   G.ALIQUOTA_PIS                                                                               AS ALIQUOTA_PIS,
	   G.ALIQUOTA_COFINS                                                                            AS ALIQUOTA_COFINS,
	   IIF(((E.PRECO_VENDA - AVG(D.CUSTO_CONTABIL)) / E.PRECO_VENDA) < 0.20, 'PRECO ERRADO','OK')	AS SITUACAO
	FROM PRODUTOS												AS A
		INNER JOIN PRODUTOS_EAN									AS B ON A.PRODUTO = B.PRODUTO
		INNER JOIN MARCAS										AS C ON A.MARCA   = C.MARCA
		LEFT  JOIN CUSTO_MEDIO_MENSAL_EMPRESA_CUSTO				AS D ON A.PRODUTO = D.PRODUTO
		LEFT  JOIN PRODUTOS_VENDAS								AS E ON A.PRODUTO = E.PRODUTO
		LEFT  JOIN EMPRESAS_USUARIAS							AS F ON D.EMPRESA_CUSTO = F.EMPRESA_USUARIA
		LEFT  JOIN PRODUTOS_PARAMETROS_TRIBUTARIOS_TERCEIROS    AS G ON A.PRODUTO = G.PRODUTO

	WHERE B.EAN_PRINCIPAL = 'S' AND
		  D.MES = MONTH(GETDATE()) AND
		  D.ANO = YEAR(GETDATE()) AND
		  E.GRUPO_PRECO = 1 AND
		  F.COMPRA_DIRETA = 'S' AND
		  G.OPERACAO_FISCAL = 28 AND
		  G.ESTADO_EMPRESA = 'SP' AND
		  A.PRODUTO = 248625 
     GROUP BY A.PRODUTO,
	          A.DESCRICAO,
			  B.EAN,
			  C.DESCRICAO,
			  E.PRECO_FABRICA,
			  E.DESCONTO_PADRAO,
			  E.PRECO_VENDA,
			  G.ALIQUOTA_ICMS,
			  G.ALIQUOTA_PIS,
			  G.ALIQUOTA_COFINS
